# alacritty.toml
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual

#import = [
#"~/.config/alacritty/catpuccin-mocha.toml",
#"~/.config/alacritty/keybindings.toml",
#]

[shell]
program               = "zsh"
args                  = [ "--login", ]

#working_directory     = "None"
#live_config_reload    = true
#ipc_socket            = true

[env]
TERM                  = "xterm-256color"

[window]
#dimensions            = { columns = 0, lines = 0 }
#position              = { x = 0, y = 0 }
#padding               = { x = 2, y = 2 }
#dynamic_padding       = true
#decorations           = "None"
#opacity               = 1.0
#blur                  = true
#startup_mode          = "Windowed"
#title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"


[scrolling]
history               = 65535
#multiplier            = 3

[font]
size                  = 10
normal                = { family = "DejaVuSansM Nerd Font Mono", style = "Regular" }
bold                  = { family = "DejaVuSansM Nerd Font Mono", style = "Bold" }
italic                = { family = "DejaVuSansM Nerd Font Mono", style = "Italic" }
bold_italic           = { family = "DejaVuSansM Nerd Font Mono", style = "Bold Italic" }
#normal                = { family = "FantasqueSansMNerdFont Propo", style = "Regular" }
#bold                  = { family = "FantasqueSansMNerdFont Propo", style = "Bold" }
#italic                = { family = "FantasqueSansMNerdFont Propo", style = "Italic" }
#bold_italic           = { family = "FantasqueSansMNerdFont Propo", style = "Bold Italic" }
#offset                = { x = 0, y = 0 }
#glyph_offset          = { x = 0, y = 0 }
#builtin_box_drawing   = true

[bell]
#animation             = "EaseOutExpo"
#duration              = 0
#color                 = "#C0C5CE"
#command               = { program = "notify-send", args = ["alacritty", "bell",] }

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
#shape                 = "Beam"
#blinking              = "Always"

[cursor.vi_mode_style]
#shape                 = "Block"
#blinking              = "Off"

[cursor]
#blink_interval        = 500
#Blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
#hide_when_typing      = true
#bindings = [
  #{ mouse = "Middle", action = "PasteSelection" },
#]

[hints]
alphabet              = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command               = "xdg-open"
## command             = "open" # On macOS
## command             = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks            = true
post_processing       = true
#persist               = false
mouse.enabled         = true
binding               = { key = "U", mods = "Control|Shift" }
regex                 = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
#bindings = [
  #{ key = "V",        mods = "Control|Shift", action = "Paste" },
  #{ key = "C",        mods = "Control|Shift", action = "Copy" },
  #{ key = "Paste",                            action = "Paste" },
  #{ key = "Copy",                             action = "Copy" },
  #{ key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  #{ key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  #{ key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  #{ key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  #{ key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  #{ key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  #{ key = "L",        mods = "Control",       action = "ClearLogNotice" },
  #{ key = "L",        mods = "Control",       chars  = "\f" },
  #{ key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  #{ key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  #{ key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  #{ key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  #{ key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  #{ key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
#]


[debug]
#render_timer          = false
#persistent_logging    = false
#log_level             = "Warn"
#renderer              = "None"
#print_events          = false
#highlight_damage      = false
#prefer_egl            = false


# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'
